### ISSUE TITLE
Integrate with Photos App

### ISSUE THREAD

**Issue by franciscoamado** [KrauseFx/overkill#1]
Hi!

Just for convenience, you could expand this with the Photos App to prevent it from openning when connecting a device.

Thanks,
Francisco

**Comment by KrauseFx** [comment]
Hey, thanks for the issue. Already done, just enable it ☺ https://github.com/KrauseFx/overkill/blob/master/overkill.rb

**Comment by franciscoamado** [comment]
😬 Didn't noticed it! Thanks!

**Comment by KrauseFx** [comment]
If you want to use a persistent and less _overkill_ approach, you can as well disable Photo launch for all devices using user defaults: ```defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool YES```
